function ArgumentException(msg) {
    return {
        name: 'ArgumentException',
        message: msg
    };
};